spring:
  application:
    name: service-eureka-server
    
server:
  port: 8761

# Si se necesita que además este servidor de ureka sea un cliente no es 
# necesario realizar las siguiente configuracións
eureka:
  client:
    register-with-eureka: false 
    fetch-registry: false
#  server:
#    enable-self-preservation: false
